### ISSUE TITLE
nicer error page for missing start parameters

### ISSUE THREAD

**Issue by kakulukia** [23andMe/djdt-flamegraph#6]
Did someone already try to make a nicer error message for the "signal only works in main thread" error?

If its possible id like it to just remind to add "--nothreading --noreload" before activating this djdt panel. I offer myself for implementing this, but as i have just a bare knowledge about this threading stuff, i better ask before running into dead ends. :)

**Comment by kakulukia** [comment]
awesome project tho .. just head about flamegraphs a few minutes ago and had to test it out! :D

**Comment by blopker** [comment]
It's hard to add this kind of error since there's no easy way to know what arguments the server was run with. If you find a way let me know!

**Comment by kakulukia** [comment]
Okay the start parameter might be hard. What about catching the above error?

**Comment by mverleg** [comment]
> there's no easy way to know what arguments the server was run with

@blopker Isn't is inside `sys.argv` in many cases?

P.s.: I, too, think it is a nice project
