### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' when this package is installed.

### ISSUE THREAD

**Issue by craiga** [23andMe/djdt-flamegraph#7]
Installing the flame graph panel causes an `AttributeError`.

```
AttributeError
Exception Value: 'NoneType' object has no attribute 'get'

File "…/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)
File "…/debug_toolbar/middleware.py" in __call__
  69.         content_encoding = response.get("Content-Encoding", "")
```

[According to the documentation, `process_request` should return a response](https://django-debug-toolbar.readthedocs.io/en/latest/panels.html#debug_toolbar.panels.Panel.process_request) which it doesn't look like this panel is doing.

**Comment by ianzapolsky** [comment]
Hey @craiga - did you ever find a solution to this? I'm seeing the exact same.

**Comment by ianzapolsky** [comment]
I found that after modifying `process_request` as shown below, an exception is no longer raised:
```
def process_request(self, request):
    self.sampler.start()
    return super().process_request(request)
```

**Comment by craiga** [comment]
@ianzapolsky I didn't, and thanks for the fix … is this something you can put into a pull request?

If not, I'll try putting something together the next time I'm messing about with the debug toolbar (I'm not doing much Django work at the moment so it's unlikely to be any time soon).

**Comment by ianzapolsky** [comment]
Sure, I'll put something up.

**Comment by Asday** [comment]
This can be closed now, right @craiga?

**Comment by craiga** [comment]
Yep!
